# Generated by Django 3.0.6 on 2020-05-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ticker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticker', to='Ticker.StockMetaData'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='volume',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('RSI_14D', models.FloatField()),
                ('Volume_plain', models.FloatField()),
                ('BB_Middle_Band', models.FloatField()),
                ('BB_Upper_Band', models.FloatField()),
                ('BB_Lower_Band', models.FloatField()),
                ('Aroon_Oscillator', models.FloatField()),
                ('PVT', models.FloatField()),
                ('AB_Middle_Band', models.FloatField()),
                ('AB_Upper_Band', models.FloatField()),
                ('AB_Lower_Band', models.FloatField()),
                ('STOK', models.FloatField()),
                ('STOD', models.FloatField()),
                ('Chaikin_MF', models.FloatField()),
                ('psar', models.FloatField()),
                ('ROC', models.FloatField()),
                ('VWAP', models.FloatField()),
                ('Momentum', models.FloatField()),
                ('CCI', models.FloatField()),
                ('OBV', models.FloatField()),
                ('Kelch_Upper', models.FloatField()),
                ('Kelch_Middle', models.FloatField()),
                ('Kelch_Down', models.FloatField()),
                ('TEMA', models.FloatField()),
                ('NATR', models.FloatField()),
                ('plusDI', models.FloatField()),
                ('minusDI', models.FloatField()),
                ('ADX', models.FloatField()),
                ('MACD', models.FloatField()),
                ('Money_Flow_Index', models.FloatField()),
                ('turning_line', models.FloatField()),
                ('standard_line', models.FloatField()),
                ('ichimoku_span1', models.FloatField()),
                ('ichimoku_span2', models.FloatField()),
                ('chikou_span', models.FloatField()),
                ('WillR', models.FloatField()),
                ('MIN_Volume', models.FloatField()),
                ('MAX_Volume', models.FloatField()),
                ('KAMA', models.FloatField()),
                ('ticker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='Ticker.Ticker')),
            ],
        ),
    ]
