# Generated by Django 3.0.6 on 2020-05-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticker', '0003_auto_20200519_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='date',
            field=models.CharField(max_length=32),
        ),
    ]
